# ansible-playbook -i "myhost," --extra-vars "radicale_user=<myuser>" --extra-vars "radicale_htaccess_pass=<htapass>" --ask-become-pass
---
- hosts: [] # add hosts on CLI with -i "myhost,"
  vars:
  - radicale_user: pi # overwrite on CLI with --extra-vars "radicale_user=<myuser>"
  - radicale_htaccess_pass: secret # overwrite on CLI with --extra-vars "radicale_htaccess_pass=<mypass>"
  - radicale_dir: "/home/{{ radicale_user }}/radicale"
  - backups_dir: "{{ radicale_dir }}/backups"
  remote_user: "{{ radicale_user }}"
  tasks:
  - name: install prerequisites
    apt: name={{ item }} state=latest
    with_items:
      - python3-pip
      - nginx
      - openssl
      - rsync
    become: true
  - name: install radicale
    command: python3 -m pip install --upgrade radicale --user
  - name: make radicale dir
    file: path={{ radicale_dir }} state=directory
  - name: radicale.conf
    copy: src=radicale.conf dest={{ radicale_dir }}/radicale.conf
  - name: logging.conf
    copy: src=logging.conf dest={{ radicale_dir }}/logging.conf
  - name: radicale start script wrapper
    template: src=start-radicale.sh dest={{ radicale_dir }}/start-radicale.sh mode=0700
  - name: start radicale
    command: "{{ radicale_dir }}/start-radicale.sh"
  - name: create htaccess file
    template: src=users.radicale.j2 dest={{ radicale_dir }}/users.radicale mode=0644
  - name: add password to htaccess file
    shell: echo "{{ radicale_htaccess_pass }}" | openssl passwd -stdin -apr1 >> {{ radicale_dir }}/users.radicale
  - name: nginx reverse proxy conf
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/reverse-proxy.conf
    become: true
    notify:
      - restart nginx
  - name: symlink nginx conf
    file: src=/etc/nginx/sites-available/reverse-proxy.conf dest=/etc/nginx/sites-enabled/reverse-proxy.conf state=link
    become: true
    notify:
      - restart nginx
  - name: disable default site
    file: path=/etc/nginx/sites-enabled/default state=absent
    become: true
    notify:
      - restart nginx
  - name: poor man's backup dir
    file: path={{ backups_dir }} state=directory
  - name: poor man's backups via cron
    cron: user={{ radicale_user }} job="rsync -r {{ radicale_dir }}/collections/ {{ backups_dir }}/" minute="0" hour="5" name="Back up radicale calendars"
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
    become: true