# ssh_user is used for both Ansible and SSH afterwards.
# This means it needs sudo for configuration, but should not be allowed (password-less)
# sudo privileges when being used for SSH connections afterwards.
# Therefore, sudo commands during deployment should ask for a password.

# ansible-playbook -i "myhost," --ask-become-pass --extra-vars "ssh_user=<myuser>"
---
- hosts: [] # add hosts on CLI with -i "myhost,"
  vars:
  - ssh_user: pi # overwrite on CLI with --extra-vars "ssh_user=<myuser>"
  remote_user: "{{ ssh_user }}"
  tasks:
  - name: sshd config # make sure keys have been copied before
    template: src=sshd_config.j2 dest=/etc/ssh/sshd_config mode=0644
    become: true
    notify:
      - restart sshd
  handlers:
  - name: restart sshd
    service: name=ssh state=restarted
    become: true
